// File generated by FlutterFire CLI.
// If Firebase project settings ever change, re-run `flutterfire configure`
// from the project root to regenerate this file (and
// android/app/google-services.json / ios/Runner/GoogleService-Info.plist).
// See CLAUDE.md → "Firebase kurulumu" for the full setup steps.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run `flutterfire configure` to generate this file.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform - '
          'run `flutterfire configure` to generate this file.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8rJ3ZKU-3JgBFlsN7gSBCFUqXegR0qFA',
    appId: '1:192386661850:android:107e0fcc9fbe19bfd2d4e3',
    messagingSenderId: '192386661850',
    projectId: 'is-takip-d8ae1',
    storageBucket: 'is-takip-d8ae1.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2AESXrVrxSfOQxxE18SA8zVDoARHXqRs',
    appId: '1:192386661850:ios:9ec5cf4f63104aa9d2d4e3',
    messagingSenderId: '192386661850',
    projectId: 'is-takip-d8ae1',
    storageBucket: 'is-takip-d8ae1.firebasestorage.app',
    iosBundleId: 'com.ahmet.istakip',
  );
}
